config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :food_items
  get 'menu' => 'home#menu'

  get 'contact_us' => 'home#contact_us'

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  belongs_to :section
  validates :name, :price, presence: true
  has_many :orders
  
  def image_url_or_default
    (!image_url.nil? && !image_url.blank?)? image_url : "http://toinayangi.vn/wp-content/uploads/2017/09/cach-lam-com-ga-tay-cam-1.jpg"
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :food_item
  validates :quantity, presence: true, numericality: true
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :food_items, dependent: :destroy

  def to_s
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :set_food_item, only: [:show, :edit, :update, :destroy]

  # GET /food_items
  # GET /food_items.json
  def index
    @food_items = FoodItem.all
  end

  # GET /food_items/1
  # GET /food_items/1.json
  def show
    
  end

  # GET /food_items/new
  def new
    @food_item = FoodItem.new
  end

  # GET /food_items/1/edit
  def edit
  end

  # POST /food_items
  # POST /food_items.json
  def create
    @food_item = FoodItem.new(food_item_params)

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: 'Food item was successfully created.' }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_items/1
  # PATCH/PUT /food_items/1.json
  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to @food_item, notice: 'Food item was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1
  # DELETE /food_items/1.json
  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to food_items_url, notice: 'Food item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_item_params
      params.require(:food_item).permit(:name, :description, :price, :section_id, :image_url)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def contact_us
  end

  
  def menu
    @sections = Section.all
    if params[:section_name].present?
      @current_section = Section.find_by_name(params[:section_name])
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  def new
    @item = FoodItem.find(params[:food_item_id])
    @order = @item.orders.build 
  end

  def create
    @item = FoodItem.find(params[:food_item_id])
    @order = @item.orders.build order_params
    # raise "hello"
    if @order.save
      redirect_to menu_path, flash: {success: "thanks you for your order."}
    else 
      render 'new'
    end
  end

  def order_params
    params.require(:order).permit(:quantity)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/food_items/_form.html.erb
<%= form_with(model: food_item, local: true) do |form| %>
  <% if food_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food_item.errors.count, "error") %> prohibited this food_item from being saved:</h2>

      <ul>
      <% food_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :food_item_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :food_item_description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :food_item_price %>
  </div>

  <div class="field">
    <%= form.label :section_id %>
    <!--use reject to remove a object of map-->
    <%= form.select :section_id, Section.all.reject{|e| (e.name === "All")}.map{|e| [e.name, e.id]} %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :food_item_image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/food_items/edit.html.erb
<h1>Editing Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Show', @food_item %> 
<%= link_to 'Back', food_items_path %>

app/views/food_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Food Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Section</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_items.each do |food_item| %>
      <tr>
        <td><%= food_item.name %></td>
        <td><%= food_item.description %></td>
        <td><%= food_item.price %></td>
        <td><%= food_item.section.name %></td>
        <td><%= food_item.image_url %></td>
        <td><%= link_to 'Show', food_item %></td>
        <td><%= link_to 'Edit', edit_food_item_path(food_item) %></td>
        <td><%= link_to 'Destroy', food_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food Item', new_food_item_path %>

app/views/food_items/new.html.erb
<h1>New Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Back', food_items_path %>

app/views/food_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food_item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @food_item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @food_item.price %>
</p>

<p>
  <strong>Section:</strong>
  <%= @food_item.section.name %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @food_item.image_url %>
</p>

<%= link_to 'Edit', edit_food_item_path(@food_item) %> |
<%= link_to 'Back', food_items_path %>

app/views/home/contact_us.html.erb
<h1>Hoang Restaurant</h1>

<div class="row">
  <div class="col-sm-6">
    <div class="card card-block">
      <address>
        <strong> Hoang Restaurant</strong><br>
        <strong>72 Lê Thánh Tôn, Bến Nghé, Quận 1, Hồ Chí Minh</strong><br>
      </address>
    </div>
  </div>   
  <div class="col-sm-6">
    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15677.731662199227!2d106.7015847!3d10.7781174!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x3ac4570b9f850ad9!2swww.cohibacigarettes.com!5e0!3m2!1sen!2s!4v1523549347300" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
  </div>
</div>

app/views/home/index.html.erb
<h1>Welcome to Hoang Restaurant</h1>
<div class="jumbotron hero">
  <%= link_to "Menu" , 'menu', class: 'btn btn-secondary' %>
  <%= link_to "Contact Us" , 'contact_us', class: 'btn btn-secondary' %>
</div>

app/views/home/menu.html.erb
<h1>Menu</h1>
<div class="btn-group">
  <% @sections.each do |section| %>
    <%= link_to section.name, menu_path(section_name: section.name), class: "btn #{params[:section_name] == section.name ? 'btn-primary' : 'btn-secondary'}"%>
  <% end %>
</div>

<% if @current_section %>
  <table class="table">
    <thread>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Image</th>
      </tr>
    </thread>
    <div class="tbody">
      <%if @current_section.food_items.count > 0 %>
        <% @current_section.food_items.each do |item|%>
        <tr>
          <td><%= item.name %></td>
          <td><%= number_to_currency item.price %></td>
          <td><%= image_tag item.image_url_or_default%></td>
          <td><%= link_to "Add to other", new_order_path(food_item_id: item.id) %>
        </tr>
        <% end %>
      <% end %>
    </div>
  </table>
<% else %>
  <div class="alert alert-info">Please select a section</div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%=root_path%>">PH</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrestaurant</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/navbar' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/new.html.erb
<h1>Order for <%= @item.name %></h1>


<%= form_for @order, url: orders_path(food_item_id: @item.id) do |f| %>
  <% if @order.errors.present? %>
    <div class="alert alert-danger">
      <%= @order.errors.full_messages.to_sentence %>
      </div>
  <% end %>
  <div class="form-group">
    <%= f.label :quantity%>
    <%= f.number_field :quantity, class: 'form-control'%>
  </div>
  <%= f.submit nil, class: 'btn btn-primary'%>
<%end%>